GET http://localhost:4000/api/product

###

GET http://localhost:4000/api/product/6082b60b24a3c921ddcc2cfa

###

POST http://localhost:4000/api/product/
Content-Type: application/json

{
    "title": "Yellow Cuts",
    "description": "Grafisk illustration med vita former som bildar ett abstrakt mönster på en gul bakgrund.",
    "size": "50 x 70 cm",
    "price": 350,
    "image": "https://desenio.se/bilder/artiklar/zoom/14650_2.jpg?imgwidth=435&qt=Abstrakta%20former",
    "path": "yellow-cuts",
    "category": "abstract",
    "stock": 10
}
###

PUT http://localhost:4000/api/product/60a3817fe9a614153eee3092
Content-Type: application/json

{
    "title": "",
    "description": "",
    "size": "",
    "price": 0,
    "image": "",
    "path": "",
    "category": "",
    "stock": 0
}

###
DELETE http://localhost:4000/api/product/60a38cd48d627617d5ae19a7