GET http://localhost:4000/api/product

###

GET http://localhost:4000/api/product/6082b60b24a3c921ddcc2cfa

###

POST http://localhost:4000/api/product/
Content-Type: application/json

{
    "title": "Yellow Cuts",
    "description": "Graphic illustration with white shapes forming an abstract pattern on a yellow background. Give your home that feeling of a modern art museum with this abstract art print!",
    "size": "50 x 70 cm",
    "price": 350,
    "image": "../images/yellow-cuts.jpg",
    "path": "yellow-cuts",
    "categories": ["graphic", "abstract"], 
    "stock": 10
}
###

PUT http://localhost:4000/api/product/60a3817fe9a614153eee3092
Content-Type: application/json

{
    "title": "",
    "description": "",
    "size": "",
    "price": 0,
    "image": "",
    "path": "",
    "categories": "",
    "stock": 10
}

###
DELETE http://localhost:4000/api/product/60a38cd48d627617d5ae19a7


###
GET http://localhost:4000/api/product/categories