GET http://localhost:4000/api/user/

###
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
    "role": "admin",
    "username": "dede",
    "password": "password"
}

###
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "username": "dede",
    "password": "password"
}

###
DELETE http://localhost:4000/api/user/logout

###
POST http://localhost:4000/api/user/authenticate